package view;

import controller.AdminController;
import model.DoctorProfile;
import model.TreatmentType;
import model.User;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 * NetBeans GUI Builder form (paired AdminDashboardView.form) - edit via Design tab.
 */
public class AdminDashboardView extends JFrame {

    private final AdminController adminController = new AdminController();
    private final User currentAdmin;

    private final DefaultTableModel doctorTableModel =
            new DefaultTableModel(new Object[]{"ID", "Name", "Specialization", "Contact", "Fee", "Available"}, 0) {
                public boolean isCellEditable(int r, int c) { return false; }
            };
    private final DefaultTableModel receptionTableModel =
            new DefaultTableModel(new Object[]{"ID", "Username", "Name", "Contact"}, 0) {
                public boolean isCellEditable(int r, int c) { return false; }
            };
    private final DefaultTableModel treatmentTableModel =
            new DefaultTableModel(new Object[]{"ID", "Name", "Cost"}, 0) {
                public boolean isCellEditable(int r, int c) { return false; }
            };

    public AdminDashboardView(User currentAdmin) {
        this.currentAdmin = currentAdmin;
        setTitle("Admin Dashboard - " + currentAdmin.getFullName());
        initComponents();
        installDashboardHeader();
        tabs.addTab("Appointment Search", new AppointmentSearchPanel());
        doctorTable.setModel(doctorTableModel);
        receptionTable.setModel(receptionTableModel);
        treatmentTable.setModel(treatmentTableModel);
        tabs.setTitleAt(0, "Doctors");
        tabs.setTitleAt(1, "Reception staff");
        tabs.setTitleAt(2, "Treatments");
        UITheme.style(this);
        setSize(800, 520);
        setLocationRelativeTo(null);
        refreshAll();
    }

    private void installDashboardHeader() {
        java.awt.Container dashboardContent = getContentPane();
        JPanel shell = new JPanel(new java.awt.BorderLayout(0, 10));
        JPanel header = new JPanel(new java.awt.BorderLayout(12, 0));
        header.setBorder(BorderFactory.createEmptyBorder(4, 8, 2, 8));

        JLabel heading = new JLabel("Dental Clinic Administration");
        heading.setFont(heading.getFont().deriveFont(java.awt.Font.BOLD, 20f));
        heading.setForeground(UITheme.PRIMARY_DARK);

        JButton reportsButton = new JButton("Reports");
        reportsButton.setToolTipText("Open daily appointment and monthly revenue reports");
        reportsButton.addActionListener(event -> new AdminReportsView().setVisible(true));

        header.add(heading, java.awt.BorderLayout.WEST);
        header.add(reportsButton, java.awt.BorderLayout.EAST);
        shell.add(header, java.awt.BorderLayout.NORTH);
        shell.add(dashboardContent, java.awt.BorderLayout.CENTER);
        setContentPane(shell);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        doctorsPanel = new javax.swing.JPanel();
        doctorScrollPane = new javax.swing.JScrollPane();
        doctorTable = new javax.swing.JTable();
        addDoctorButton = new javax.swing.JButton();
        toggleAvailabilityButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        receptionPanel = new javax.swing.JPanel();
        receptionScrollPane = new javax.swing.JScrollPane();
        receptionTable = new javax.swing.JTable();
        addReceptionButton = new javax.swing.JButton();
        treatmentPanel = new javax.swing.JPanel();
        treatmentScrollPane = new javax.swing.JScrollPane();
        treatmentTable = new javax.swing.JTable();
        treatmentNameLabel = new javax.swing.JLabel();
        treatmentNameField = new javax.swing.JTextField();
        treatmentCostLabel = new javax.swing.JLabel();
        treatmentCostField = new javax.swing.JTextField();
        treatmentAddButton = new javax.swing.JButton();
        treatmentDeleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        doctorScrollPane.setViewportView(doctorTable);

        addDoctorButton.setText("Add Doctor");
        addDoctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDoctorButtonActionPerformed(evt);
            }
        });

        toggleAvailabilityButton.setText("Toggle Availability");
        toggleAvailabilityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleAvailabilityButtonActionPerformed(evt);
            }
        });

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout doctorsPanelLayout = new javax.swing.GroupLayout(doctorsPanel);
        doctorsPanel.setLayout(doctorsPanelLayout);
        doctorsPanelLayout.setHorizontalGroup(
            doctorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doctorsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(doctorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(doctorsPanelLayout.createSequentialGroup()
                        .addComponent(doctorScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(doctorsPanelLayout.createSequentialGroup()
                        .addComponent(addDoctorButton)
                        .addGap(18, 18, 18)
                        .addComponent(toggleAvailabilityButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108))))
        );
        doctorsPanelLayout.setVerticalGroup(
            doctorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doctorsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(doctorScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(doctorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addDoctorButton)
                    .addComponent(toggleAvailabilityButton)
                    .addComponent(logoutButton))
                .addContainerGap())
        );

        tabs.addTab("tab1", doctorsPanel);

        receptionScrollPane.setViewportView(receptionTable);

        addReceptionButton.setText("Add Reception Staff");
        addReceptionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addReceptionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout receptionPanelLayout = new javax.swing.GroupLayout(receptionPanel);
        receptionPanel.setLayout(receptionPanelLayout);
        receptionPanelLayout.setHorizontalGroup(
            receptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receptionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(receptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(receptionScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                    .addGroup(receptionPanelLayout.createSequentialGroup()
                        .addComponent(addReceptionButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        receptionPanelLayout.setVerticalGroup(
            receptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receptionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(receptionScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addReceptionButton)
                .addContainerGap())
        );

        tabs.addTab("tab2", receptionPanel);

        treatmentScrollPane.setViewportView(treatmentTable);

        treatmentNameLabel.setText("Name:");

        treatmentCostLabel.setText("Cost (Rs.):");

        treatmentAddButton.setText("Add");
        treatmentAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treatmentAddButtonActionPerformed(evt);
            }
        });

        treatmentDeleteButton.setText("Delete Selected");
        treatmentDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treatmentDeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout treatmentPanelLayout = new javax.swing.GroupLayout(treatmentPanel);
        treatmentPanel.setLayout(treatmentPanelLayout);
        treatmentPanelLayout.setHorizontalGroup(
            treatmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(treatmentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(treatmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(treatmentScrollPane)
                    .addGroup(treatmentPanelLayout.createSequentialGroup()
                        .addComponent(treatmentNameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(treatmentNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(treatmentCostLabel)
                        .addGap(18, 18, 18)
                        .addComponent(treatmentCostField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(treatmentAddButton)
                        .addGap(18, 18, 18)
                        .addComponent(treatmentDeleteButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        treatmentPanelLayout.setVerticalGroup(
            treatmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(treatmentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(treatmentScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(treatmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(treatmentNameLabel)
                    .addComponent(treatmentNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(treatmentCostLabel)
                    .addComponent(treatmentCostField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(treatmentAddButton)
                    .addComponent(treatmentDeleteButton))
                .addContainerGap())
        );

        tabs.addTab("tab3", treatmentPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addDoctorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDoctorButtonActionPerformed
        AddDoctorDialog dialog = new AddDoctorDialog(this, adminController);
        dialog.setVisible(true);
        if (dialog.wasCreated()) refreshDoctors();
    }//GEN-LAST:event_addDoctorButtonActionPerformed

    private void toggleAvailabilityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleAvailabilityButtonActionPerformed
        int row = doctorTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select a doctor first");
            return;
        }
        int id = (int) doctorTableModel.getValueAt(row, 0);
        boolean currentlyAvailable = "Yes".equals(doctorTableModel.getValueAt(row, 5));
        adminController.setDoctorAvailability(id, !currentlyAvailable);
        refreshDoctors();
    }//GEN-LAST:event_toggleAvailabilityButtonActionPerformed

    private void addReceptionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addReceptionButtonActionPerformed
        AddReceptionDialog dialog = new AddReceptionDialog(this, adminController);
        dialog.setVisible(true);
        if (dialog.wasCreated()) refreshReception();
    }//GEN-LAST:event_addReceptionButtonActionPerformed

    private void treatmentAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treatmentAddButtonActionPerformed
        try {
            adminController.addTreatmentType(treatmentNameField.getText().trim(), Double.parseDouble(treatmentCostField.getText().trim()));
            treatmentNameField.setText("");
            treatmentCostField.setText("");
            refreshTreatmentTypes();
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Cost must be a number");
        }
    }//GEN-LAST:event_treatmentAddButtonActionPerformed

    private void treatmentDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treatmentDeleteButtonActionPerformed
        int row = treatmentTable.getSelectedRow();
        if (row == -1) return;
        int id = (int) treatmentTableModel.getValueAt(row, 0);
        adminController.deleteTreatmentType(id);
        refreshTreatmentTypes();
    }//GEN-LAST:event_treatmentDeleteButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
         int choice = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to log out?",
            "Confirm Logout",
            JOptionPane.YES_NO_OPTION
        );

        if (choice == JOptionPane.YES_OPTION) {
        new LoginView().setVisible(true);
        dispose();
        }
    }//GEN-LAST:event_logoutButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDoctorButton;
    private javax.swing.JButton addReceptionButton;
    private javax.swing.JScrollPane doctorScrollPane;
    private javax.swing.JTable doctorTable;
    private javax.swing.JPanel doctorsPanel;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel receptionPanel;
    private javax.swing.JScrollPane receptionScrollPane;
    private javax.swing.JTable receptionTable;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JButton toggleAvailabilityButton;
    private javax.swing.JButton treatmentAddButton;
    private javax.swing.JTextField treatmentCostField;
    private javax.swing.JLabel treatmentCostLabel;
    private javax.swing.JButton treatmentDeleteButton;
    private javax.swing.JTextField treatmentNameField;
    private javax.swing.JLabel treatmentNameLabel;
    private javax.swing.JPanel treatmentPanel;
    private javax.swing.JScrollPane treatmentScrollPane;
    private javax.swing.JTable treatmentTable;
    // End of variables declaration//GEN-END:variables

    private void refreshAll() {
        refreshDoctors();
        refreshReception();
        refreshTreatmentTypes();
    }

    private void refreshDoctors() {
        doctorTableModel.setRowCount(0);
        List<DoctorProfile> doctors = adminController.listDoctors();
        for (DoctorProfile d : doctors) {
            doctorTableModel.addRow(new Object[]{
                    d.getId(), d.getFullName(), d.getSpecialization(), d.getContactNumber(),
                    d.getConsultationFee(), d.isAvailable() ? "Yes" : "No"
            });
        }
    }

    private void refreshReception() {
        receptionTableModel.setRowCount(0);
        List<User> receptionStaff = adminController.listReception();
        for (User u : receptionStaff) {
            receptionTableModel.addRow(new Object[]{u.getId(), u.getUsername(), u.getFullName(), u.getContactNumber()});
        }
    }

    private void refreshTreatmentTypes() {
        treatmentTableModel.setRowCount(0);
        List<TreatmentType> types = adminController.listTreatmentTypes();
        for (TreatmentType t : types) {
            treatmentTableModel.addRow(new Object[]{t.getId(), t.getName(), t.getCost()});
        }
    }
}
