package view;

import model.Appointment;

import javax.swing.*;
import java.awt.print.PrinterException;

/**
 * Shown once a doctor has ACCEPTED an appointment: the token to hand the patient + the bill.
 * NetBeans GUI Builder form (paired BillView.form) - edit via Design tab.
 */
public class BillView extends JDialog {

    public BillView(JFrame parent, Appointment appt) {
        super(parent, "Bill / Token - " + appt.getAppointmentNumber(), true);
        initComponents();
        billArea.setFont(new java.awt.Font(java.awt.Font.MONOSPACED, java.awt.Font.PLAIN, 13));
        billArea.setText(buildBillText(appt));
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        billScrollPane = new javax.swing.JScrollPane();
        billArea = new javax.swing.JTextArea();
        printButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        billArea.setColumns(20);
        billArea.setEditable(false);
        billArea.setRows(5);
        billScrollPane.setViewportView(billArea);

        printButton.setText("Print");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(billScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(printButton)
                        .addGap(18, 18, 18)
                        .addComponent(closeButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(billScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printButton)
                    .addComponent(closeButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        try {
            billArea.print();
        } catch (PrinterException ex) {
            JOptionPane.showMessageDialog(this, "Could not print: " + ex.getMessage());
        }
    }//GEN-LAST:event_printButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea billArea;
    private javax.swing.JScrollPane billScrollPane;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton printButton;
    // End of variables declaration//GEN-END:variables

    private String buildBillText(Appointment a) {
        StringBuilder sb = new StringBuilder();
        sb.append("        DENTAL CLINIC - RECEIPT\n");
        sb.append("========================================\n");
        sb.append("Appointment No : ").append(a.getAppointmentNumber()).append("\n");
        sb.append("Token No       : ").append(a.getTokenNumber() == null ? "(not yet issued)" : a.getTokenNumber()).append("\n");
        sb.append("Patient        : ").append(a.getPatientName()).append("\n");
        sb.append("Contact        : ").append(a.getPatientContact()).append("\n");
        sb.append("Doctor         : ").append(a.getDoctorName()).append("\n");
        sb.append("Treatment      : ").append(a.getTreatmentTypeName()).append("\n");
        sb.append("Date / Time    : ").append(a.getAppointmentDate()).append("  ").append(a.getAppointmentTime()).append("\n");
        sb.append("----------------------------------------\n");
        sb.append(String.format("Consultation Fee : Rs. %.2f%n", a.getConsultationFee()));
        sb.append(String.format("Treatment Cost   : Rs. %.2f%n", a.getTreatmentCost()));
        sb.append("----------------------------------------\n");
        sb.append(String.format("TOTAL            : Rs. %.2f%n", a.getTotalCost()));
        sb.append("========================================\n");
        sb.append("Status: ").append(a.getStatus()).append("\n");
        return sb.toString();
    }
}
