package view;

import controller.ReceptionController;
import model.DoctorProfile;
import model.TreatmentType;
import model.User;

import javax.swing.*;
import java.sql.Date;
import java.sql.Time;

/**
 * NetBeans GUI Builder form (paired BookAppointmentDialog.form) - edit via Design tab.
 */
public class BookAppointmentDialog extends JDialog {

    private final ReceptionController receptionController;
    private final User currentUser;
    private boolean booked = false;

    public BookAppointmentDialog(JFrame parent, ReceptionController receptionController, User currentUser) {
        super(parent, "Book Appointment", true);
        this.receptionController = receptionController;
        this.currentUser = currentUser;
        initComponents();
        for (DoctorProfile d : receptionController.availableDoctors()) doctorCombo.addItem(d);
        for (TreatmentType t : receptionController.treatmentTypes()) treatmentCombo.addItem(t);
        buildFriendlyLayout();
        getRootPane().setDefaultButton(saveButton);
        UITheme.style(this);
        setMinimumSize(new java.awt.Dimension(620, 600));
        setSize(650, 650);
        setResizable(false);
        setLocationRelativeTo(parent);
    }

    private void buildFriendlyLayout() {
        JPanel root = new JPanel(new java.awt.BorderLayout(0, 14));
        root.setBorder(BorderFactory.createEmptyBorder(20, 24, 20, 24));
        JLabel title = new JLabel("Book a New Appointment");
        title.setFont(title.getFont().deriveFont(java.awt.Font.BOLD, 22f));
        title.setForeground(UITheme.PRIMARY_DARK);
        title.putClientProperty("ui.preserveForeground", Boolean.TRUE);
        JLabel help = new JLabel("Enter patient details, then choose the doctor, treatment, date and time.");
        help.setForeground(UITheme.MUTED);
        help.putClientProperty("ui.preserveForeground", Boolean.TRUE);
        JPanel heading = new JPanel();
        heading.setLayout(new BoxLayout(heading, BoxLayout.Y_AXIS));
        heading.add(title); heading.add(Box.createVerticalStrut(4)); heading.add(help);
        root.add(heading, java.awt.BorderLayout.NORTH);

        JPanel form = new JPanel(new java.awt.GridBagLayout());
        form.setBackground(UITheme.SURFACE);
        form.putClientProperty("ui.preserveBackground", Boolean.TRUE);
        form.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(UITheme.BORDER),
                BorderFactory.createEmptyBorder(15, 18, 15, 18)));
        java.awt.GridBagConstraints c = new java.awt.GridBagConstraints();
        c.insets = new java.awt.Insets(6, 7, 6, 7);
        c.fill = java.awt.GridBagConstraints.HORIZONTAL;
        addRow(form, c, 0, patientNameLabel, patientNameField);
        addRow(form, c, 1, patientContactLabel, patientContactField);
        addRow(form, c, 2, doctorLabel, doctorCombo);
        addRow(form, c, 3, treatmentLabel, treatmentCombo);
        addRow(form, c, 4, dateLabel, dateField);
        addRow(form, c, 5, timeLabel, timeField);
        addRow(form, c, 6, notesLabel, notesScrollPane);
        patientNameField.setPreferredSize(new java.awt.Dimension(350, 38));
        dateField.setPreferredSize(new java.awt.Dimension(350, 38));
        notesScrollPane.setPreferredSize(new java.awt.Dimension(350, 90));
        root.add(form, java.awt.BorderLayout.CENTER);

        JButton cancelButton = new JButton("Cancel");
        cancelButton.addActionListener(event -> dispose());
        JPanel actions = new JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 0));
        actions.add(cancelButton); actions.add(saveButton);
        root.add(actions, java.awt.BorderLayout.SOUTH);
        setContentPane(root);
    }

    private void addRow(JPanel panel, java.awt.GridBagConstraints c, int row, JLabel label,
            java.awt.Component field) {
        label.setFont(label.getFont().deriveFont(java.awt.Font.BOLD));
        c.gridy = row; c.gridx = 0; c.weightx = 0; c.anchor = java.awt.GridBagConstraints.WEST;
        panel.add(label, c);
        c.gridx = 1; c.weightx = 1;
        panel.add(field, c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientNameLabel = new javax.swing.JLabel();
        patientNameField = new javax.swing.JTextField();
        patientContactLabel = new javax.swing.JLabel();
        patientContactField = new javax.swing.JTextField();
        doctorLabel = new javax.swing.JLabel();
        doctorCombo = new javax.swing.JComboBox();
        treatmentLabel = new javax.swing.JLabel();
        treatmentCombo = new javax.swing.JComboBox();
        dateLabel = new javax.swing.JLabel();
        dateField = DateTimePicker.datePicker();
        timeLabel = new javax.swing.JLabel();
        timeField = DateTimePicker.timePicker(9, 0);
        notesLabel = new javax.swing.JLabel();
        notesScrollPane = new javax.swing.JScrollPane();
        notesArea = new javax.swing.JTextArea();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        patientNameLabel.setText("Patient name:");

        patientContactLabel.setText("Patient contact:");

        doctorLabel.setText("Doctor:");

        treatmentLabel.setText("Treatment type:");

        dateLabel.setText("Appointment date:");

        timeLabel.setText("Appointment time:");

        notesLabel.setText("Notes:");

        notesArea.setColumns(15);
        notesArea.setRows(3);
        notesScrollPane.setViewportView(notesArea);

        saveButton.setText("Book Appointment");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveButton, javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(patientContactLabel)
                            .addComponent(patientNameLabel)
                            .addComponent(doctorLabel)
                            .addComponent(treatmentLabel)
                            .addComponent(dateLabel)
                            .addComponent(timeLabel)
                            .addComponent(notesLabel))
                        .addGap(24, 24, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(notesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(doctorCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(treatmentCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(patientContactField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timeField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(14, 14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientNameLabel)
                    .addComponent(patientNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientContactLabel)
                    .addComponent(patientContactField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doctorLabel)
                    .addComponent(doctorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(treatmentLabel)
                    .addComponent(treatmentCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLabel)
                    .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeLabel)
                    .addComponent(timeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(notesLabel)
                    .addComponent(notesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(saveButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            String patientName = patientNameField.getText().trim();
            String contact = patientContactField.getText().trim();
            boolean invalidName = patientName.isEmpty();
            boolean invalidContact = !contact.isEmpty() && !contact.matches("[0-9+() -]{7,20}");
            UITheme.markInvalid(patientNameField, invalidName);
            UITheme.markInvalid(patientContactField, invalidContact);
            if (invalidName) throw new IllegalArgumentException("Patient name is required.");
            if (invalidContact) throw new IllegalArgumentException("Enter a valid contact number.");
            DoctorProfile doctor = (DoctorProfile) doctorCombo.getSelectedItem();
            TreatmentType treatment = (TreatmentType) treatmentCombo.getSelectedItem();
            if (doctor == null || treatment == null) {
                UITheme.showMessageDialog(this, "Add a doctor and treatment type first (ask an admin)",
                        "Cannot Book", JOptionPane.WARNING_MESSAGE);
                return;
            }
            Date date = DateTimePicker.sqlDate(dateField);
            Time time = DateTimePicker.sqlTime(timeField);

            var appt = receptionController.bookAppointment(
                    patientName,
                    contact,
                    doctor.getId(),
                    treatment.getId(),
                    date, time,
                    notesArea.getText(),
                    currentUser.getUsername()
            );
            UITheme.showMessageDialog(this, "Appointment booked successfully.\nNumber: " + appt.getAppointmentNumber(),
                    "Booking Complete", JOptionPane.INFORMATION_MESSAGE);
            booked = true;
            dispose();
        } catch (IllegalArgumentException dateEx) {
            UITheme.showMessageDialog(this, dateEx.getMessage(), "Check Appointment Details", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            UITheme.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    public boolean wasBooked() { return booked; }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CalendarDatePicker dateField;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JComboBox doctorCombo;
    private javax.swing.JLabel doctorLabel;
    private javax.swing.JTextArea notesArea;
    private javax.swing.JLabel notesLabel;
    private javax.swing.JScrollPane notesScrollPane;
    private javax.swing.JTextField patientContactField;
    private javax.swing.JLabel patientContactLabel;
    private javax.swing.JTextField patientNameField;
    private javax.swing.JLabel patientNameLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox<java.time.LocalTime> timeField;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JComboBox treatmentCombo;
    private javax.swing.JLabel treatmentLabel;
    // End of variables declaration//GEN-END:variables
}
