package view;

import controller.ReceptionController;
import model.DoctorProfile;
import model.TreatmentType;
import model.User;

import javax.swing.*;
import java.sql.Date;
import java.sql.Time;

/**
 * NetBeans GUI Builder form (paired BookAppointmentDialog.form) - edit via Design tab.
 */
public class BookAppointmentDialog extends JDialog {

    private final ReceptionController receptionController;
    private final User currentUser;
    private boolean booked = false;

    public BookAppointmentDialog(JFrame parent, ReceptionController receptionController, User currentUser) {
        super(parent, "Book Appointment", true);
        this.receptionController = receptionController;
        this.currentUser = currentUser;
        initComponents();
        for (DoctorProfile d : receptionController.availableDoctors()) doctorCombo.addItem(d);
        for (TreatmentType t : receptionController.treatmentTypes()) treatmentCombo.addItem(t);
        UITheme.style(this);
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientNameLabel = new javax.swing.JLabel();
        patientNameField = new javax.swing.JTextField();
        patientContactLabel = new javax.swing.JLabel();
        patientContactField = new javax.swing.JTextField();
        doctorLabel = new javax.swing.JLabel();
        doctorCombo = new javax.swing.JComboBox();
        treatmentLabel = new javax.swing.JLabel();
        treatmentCombo = new javax.swing.JComboBox();
        dateLabel = new javax.swing.JLabel();
        dateField = DateTimePicker.datePicker();
        timeLabel = new javax.swing.JLabel();
        timeField = DateTimePicker.timePicker(9, 0);
        notesLabel = new javax.swing.JLabel();
        notesScrollPane = new javax.swing.JScrollPane();
        notesArea = new javax.swing.JTextArea();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        patientNameLabel.setText("Patient name:");

        patientContactLabel.setText("Patient contact:");

        doctorLabel.setText("Doctor:");

        treatmentLabel.setText("Treatment type:");

        dateLabel.setText("Appointment date:");

        timeLabel.setText("Appointment time:");

        notesLabel.setText("Notes:");

        notesArea.setColumns(15);
        notesArea.setRows(3);
        notesScrollPane.setViewportView(notesArea);

        saveButton.setText("Book Appointment");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveButton, javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(patientContactLabel)
                            .addComponent(patientNameLabel)
                            .addComponent(doctorLabel)
                            .addComponent(treatmentLabel)
                            .addComponent(dateLabel)
                            .addComponent(timeLabel)
                            .addComponent(notesLabel))
                        .addGap(24, 24, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(notesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(doctorCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(treatmentCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(patientContactField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timeField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(14, 14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientNameLabel)
                    .addComponent(patientNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientContactLabel)
                    .addComponent(patientContactField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doctorLabel)
                    .addComponent(doctorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(treatmentLabel)
                    .addComponent(treatmentCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLabel)
                    .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeLabel)
                    .addComponent(timeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(notesLabel)
                    .addComponent(notesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(saveButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            DoctorProfile doctor = (DoctorProfile) doctorCombo.getSelectedItem();
            TreatmentType treatment = (TreatmentType) treatmentCombo.getSelectedItem();
            if (doctor == null || treatment == null) {
                JOptionPane.showMessageDialog(this, "Add a doctor and treatment type first (ask an admin)");
                return;
            }
            Date date = DateTimePicker.sqlDate(dateField);
            Time time = DateTimePicker.sqlTime(timeField);

            var appt = receptionController.bookAppointment(
                    patientNameField.getText(),
                    patientContactField.getText(),
                    doctor.getId(),
                    treatment.getId(),
                    date, time,
                    notesArea.getText(),
                    currentUser.getUsername()
            );
            JOptionPane.showMessageDialog(this, "Booked! Appointment number: " + appt.getAppointmentNumber());
            booked = true;
            dispose();
        } catch (IllegalArgumentException dateEx) {
            JOptionPane.showMessageDialog(this, "Check the date/time format or required fields:\n" + dateEx.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    public boolean wasBooked() { return booked; }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CalendarDatePicker dateField;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JComboBox doctorCombo;
    private javax.swing.JLabel doctorLabel;
    private javax.swing.JTextArea notesArea;
    private javax.swing.JLabel notesLabel;
    private javax.swing.JScrollPane notesScrollPane;
    private javax.swing.JTextField patientContactField;
    private javax.swing.JLabel patientContactLabel;
    private javax.swing.JTextField patientNameField;
    private javax.swing.JLabel patientNameLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox<java.time.LocalTime> timeField;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JComboBox treatmentCombo;
    private javax.swing.JLabel treatmentLabel;
    // End of variables declaration//GEN-END:variables
}
