package view;

import controller.DoctorController;
import model.Appointment;
import model.DoctorProfile;
import model.Schedule;
import model.User;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 * NetBeans GUI Builder form (paired DoctorDashboardView.form) - edit via Design tab.
 */
public class DoctorDashboardView extends JFrame {

    private final DoctorController doctorController = new DoctorController();
    private final User currentUser;
    private final DoctorProfile myProfile;
    private List<Appointment> currentAppointments;

    private final DefaultTableModel apptModel = new DefaultTableModel(
            new Object[]{"Appt #", "Patient", "Treatment", "Date", "Time", "Status", "Notes"}, 0) {
        public boolean isCellEditable(int r, int c) { return false; }
    };
    private final DefaultTableModel scheduleModel = new DefaultTableModel(
            new Object[]{"ID", "Date", "Start", "End", "Available"}, 0) {
        public boolean isCellEditable(int r, int c) { return false; }
    };

    public DoctorDashboardView(User currentUser) {
        this.currentUser = currentUser;
        this.myProfile = doctorController.myProfile(currentUser.getUsername());
        setTitle("Doctor Dashboard - " + currentUser.getFullName());
        initComponents();
        if (myProfile == null) {
            JOptionPane.showMessageDialog(this, "No doctor profile found for this login. Contact admin.");
        }
        apptTable.setModel(apptModel);
        scheduleTable.setModel(scheduleModel);
        setSize(900, 520);
        setLocationRelativeTo(null);
        refreshAppointments();
        refreshSchedule();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        appointmentsPanel = new javax.swing.JPanel();
        apptScrollPane = new javax.swing.JScrollPane();
        apptTable = new javax.swing.JTable();
        approveButton = new javax.swing.JButton();
        rejectButton = new javax.swing.JButton();
        refreshAppointmentsButton = new javax.swing.JButton();
        schedulePanel = new javax.swing.JPanel();
        scheduleScrollPane = new javax.swing.JScrollPane();
        scheduleTable = new javax.swing.JTable();
        addSlotButton = new javax.swing.JButton();
        removeSlotButton = new javax.swing.JButton();

        apptScrollPane.setViewportView(apptTable);
        scheduleScrollPane.setViewportView(scheduleTable);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        approveButton.setText("Approve (Generate Token)");
        approveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveButtonActionPerformed(evt);
            }
        });

        rejectButton.setText("Reject");
        rejectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectButtonActionPerformed(evt);
            }
        });

        refreshAppointmentsButton.setText("Refresh");
        refreshAppointmentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshAppointmentsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout appointmentsPanelLayout = new javax.swing.GroupLayout(appointmentsPanel);
        appointmentsPanel.setLayout(appointmentsPanelLayout);
        appointmentsPanelLayout.setHorizontalGroup(
            appointmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appointmentsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(appointmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apptScrollPane)
                    .addGroup(appointmentsPanelLayout.createSequentialGroup()
                        .addComponent(approveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rejectButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refreshAppointmentsButton)))
                .addContainerGap())
        );
        appointmentsPanelLayout.setVerticalGroup(
            appointmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appointmentsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(apptScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(appointmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(approveButton)
                    .addComponent(rejectButton)
                    .addComponent(refreshAppointmentsButton))
                .addContainerGap())
        );

        addSlotButton.setText("Add Available Slot");
        addSlotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSlotButtonActionPerformed(evt);
            }
        });

        removeSlotButton.setText("Remove Selected Slot");
        removeSlotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeSlotButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout schedulePanelLayout = new javax.swing.GroupLayout(schedulePanel);
        schedulePanel.setLayout(schedulePanelLayout);
        schedulePanelLayout.setHorizontalGroup(
            schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(schedulePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scheduleScrollPane)
                    .addGroup(schedulePanelLayout.createSequentialGroup()
                        .addComponent(addSlotButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeSlotButton)))
                .addContainerGap())
        );
        schedulePanelLayout.setVerticalGroup(
            schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(schedulePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scheduleScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addSlotButton)
                    .addComponent(removeSlotButton))
                .addContainerGap())
        );

        tabs.addTab("My Appointments", appointmentsPanel);
        tabs.addTab("My Schedule", schedulePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void approveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveButtonActionPerformed
        Appointment selected = selectedAppointment();
        if (selected == null) return;
        doctorController.approve(selected.getId());
        refreshAppointments();
        JOptionPane.showMessageDialog(this, "Approved. Reception can now print the token/bill.");
    }//GEN-LAST:event_approveButtonActionPerformed

    private void rejectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectButtonActionPerformed
        Appointment selected = selectedAppointment();
        if (selected == null) return;
        doctorController.reject(selected.getId());
        refreshAppointments();
    }//GEN-LAST:event_rejectButtonActionPerformed

    private void refreshAppointmentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshAppointmentsButtonActionPerformed
        refreshAppointments();
    }//GEN-LAST:event_refreshAppointmentsButtonActionPerformed

    private void addSlotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSlotButtonActionPerformed
        if (myProfile == null) return;
        ScheduleDialog dialog = new ScheduleDialog(this, doctorController, myProfile.getId());
        dialog.setVisible(true);
        if (dialog.wasAdded()) refreshSchedule();
    }//GEN-LAST:event_addSlotButtonActionPerformed

    private void removeSlotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeSlotButtonActionPerformed
        int row = scheduleTable.getSelectedRow();
        if (row == -1) return;
        int id = (int) scheduleModel.getValueAt(row, 0);
        doctorController.removeSlot(id);
        refreshSchedule();
    }//GEN-LAST:event_removeSlotButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSlotButton;
    private javax.swing.JScrollPane apptScrollPane;
    private javax.swing.JTable apptTable;
    private javax.swing.JPanel appointmentsPanel;
    private javax.swing.JButton approveButton;
    private javax.swing.JButton refreshAppointmentsButton;
    private javax.swing.JButton rejectButton;
    private javax.swing.JButton removeSlotButton;
    private javax.swing.JScrollPane scheduleScrollPane;
    private javax.swing.JPanel schedulePanel;
    private javax.swing.JTable scheduleTable;
    private javax.swing.JTabbedPane tabs;
    // End of variables declaration//GEN-END:variables

    private Appointment selectedAppointment() {
        int row = apptTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select an appointment first");
            return null;
        }
        return currentAppointments.get(row);
    }

    private void refreshAppointments() {
        if (myProfile == null) return;
        currentAppointments = doctorController.myAppointments(myProfile.getId());
        apptModel.setRowCount(0);
        for (Appointment a : currentAppointments) {
            apptModel.addRow(new Object[]{
                    a.getAppointmentNumber(), a.getPatientName(), a.getTreatmentTypeName(),
                    a.getAppointmentDate(), a.getAppointmentTime(), a.getStatus(), a.getNotes()
            });
        }
    }

    private void refreshSchedule() {
        if (myProfile == null) return;
        List<Schedule> slots = doctorController.mySchedule(myProfile.getId());
        scheduleModel.setRowCount(0);
        for (Schedule s : slots) {
            scheduleModel.addRow(new Object[]{
                    s.getId(), s.getDate(), s.getStartTime(), s.getEndTime(), s.isAvailable() ? "Yes" : "No"
            });
        }
    }
}
