/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author Admin
 */
public class HelpPanel extends javax.swing.JPanel {

    /**
     * Creates new form HelpPanel
     */
    public HelpPanel() {
        initComponents();
        displayHelpInstructions();
    }
    private void displayHelpInstructions() {
    helpTextArea.setText(
            "DENTAL CLINIC MANAGEMENT SYSTEM\n"
            + "STAFF USER GUIDE\n"
            + "========================================\n\n"

            + "1. HOW TO LOG IN\n"
            + "----------------------------------------\n"
            + "1. Enter the username provided by the administrator.\n"
            + "2. Enter your password.\n"
            + "3. Click the Login button.\n"
            + "4. Contact the administrator if your login fails.\n\n"

            + "2. HOW TO BOOK AN APPOINTMENT\n"
            + "----------------------------------------\n"
            + "1. Open the Appointments tab.\n"
            + "2. Click the Book Appointment button.\n"
            + "3. Enter the patient's name and contact number.\n"
            + "4. Select the doctor and treatment type.\n"
            + "5. Enter the appointment date and time.\n"
            + "6. Add any necessary notes.\n"
            + "7. Click the Book button.\n"
            + "8. Give the generated appointment number to the patient.\n\n"

            + "3. HOW TO SEARCH FOR AN APPOINTMENT\n"
            + "----------------------------------------\n"
            + "1. Open the Appointment Search tab.\n"
            + "2. Enter the complete appointment number.\n"
            + "3. Example: APT-000001.\n"
            + "4. Click the Search button.\n"
            + "5. Review the patient and appointment information.\n\n"

            + "4. HOW TO CHECK APPOINTMENT STATUS\n"
            + "----------------------------------------\n"
            + "1. Open the Appointments tab.\n"
            + "2. Click Refresh to load the latest information.\n"
            + "3. PENDING means the doctor has not responded.\n"
            + "4. ACCEPTED means the doctor approved it.\n"
            + "5. REJECTED means the doctor rejected it.\n\n"

            + "5. HOW TO PRINT A BILL AND TOKEN\n"
            + "----------------------------------------\n"
            + "1. Wait until the appointment is ACCEPTED.\n"
            + "2. Select the appointment from the table.\n"
            + "3. Click Print Bill / Token.\n"
            + "4. Check the patient, treatment, cost and token details.\n"
            + "5. Click Print to print the document.\n\n"

            + "6. HOW TO LOG OUT\n"
            + "----------------------------------------\n"
            + "1. Click the Logout button.\n"
            + "2. Click Yes in the confirmation message.\n"
            + "3. The application will return to the login screen.\n\n"

            + "IMPORTANT INFORMATION\n"
            + "----------------------------------------\n"
            + "• Do not share your username or password.\n"
            + "• Check patient information before booking.\n"
            + "• Confirm the appointment number before printing.\n"
            + "• Log out before leaving the computer.\n"
    );

    helpTextArea.setCaretPosition(0);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        helpTextArea = new javax.swing.JTextArea();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Staff User Guide");

        helpTextArea.setEditable(false);
        helpTextArea.setColumns(60);
        helpTextArea.setLineWrap(true);
        helpTextArea.setRows(20);
        helpTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(helpTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea helpTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
