package view;

import controller.ReceptionController;
import model.Appointment;
import model.User;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 * NetBeans GUI Builder form (paired ReceptionDashboardView.form) - edit via Design tab.
 */
public class ReceptionDashboardView extends JFrame {

    private final ReceptionController receptionController = new ReceptionController();
    private final User currentUser;
    private List<Appointment> currentList;

    private final DefaultTableModel model = new DefaultTableModel(
            new Object[]{"Appt #", "Patient", "Doctor", "Treatment", "Date", "Time", "Status", "Token", "Total"}, 0) {
        public boolean isCellEditable(int r, int c) { return false; }
    };

    public ReceptionDashboardView(User currentUser) {
        this.currentUser = currentUser;
        setTitle("Reception Dashboard - " + currentUser.getFullName());
        initComponents();
        appointmentTable.setModel(model);
        setSize(950, 520);
        setLocationRelativeTo(null);
        refresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        appointmentScrollPane = new javax.swing.JScrollPane();
        appointmentTable = new javax.swing.JTable();
        bookAppointmentButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        printBillButton = new javax.swing.JButton();

        appointmentScrollPane.setViewportView(appointmentTable);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bookAppointmentButton.setText("Book Appointment");
        bookAppointmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookAppointmentButtonActionPerformed(evt);
            }
        });

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        printBillButton.setText("Print Bill / Token");
        printBillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBillButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(appointmentScrollPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bookAppointmentButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refreshButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(printBillButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(appointmentScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookAppointmentButton)
                    .addComponent(refreshButton)
                    .addComponent(printBillButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookAppointmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookAppointmentButtonActionPerformed
        BookAppointmentDialog dialog = new BookAppointmentDialog(this, receptionController, currentUser);
        dialog.setVisible(true);
        if (dialog.wasBooked()) refresh();
    }//GEN-LAST:event_bookAppointmentButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        refresh();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void printBillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBillButtonActionPerformed
        int row = appointmentTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select an appointment first");
            return;
        }
        Appointment appt = currentList.get(row);
        if (!"ACCEPTED".equals(appt.getStatus())) {
            JOptionPane.showMessageDialog(this, "The doctor hasn't approved this appointment yet.");
            return;
        }
        new BillView(this, appt).setVisible(true);
    }//GEN-LAST:event_printBillButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane appointmentScrollPane;
    private javax.swing.JTable appointmentTable;
    private javax.swing.JButton bookAppointmentButton;
    private javax.swing.JButton printBillButton;
    private javax.swing.JButton refreshButton;
    // End of variables declaration//GEN-END:variables

    private void refresh() {
        currentList = receptionController.allAppointments();
        model.setRowCount(0);
        for (Appointment a : currentList) {
            model.addRow(new Object[]{
                    a.getAppointmentNumber(), a.getPatientName(), a.getDoctorName(), a.getTreatmentTypeName(),
                    a.getAppointmentDate(), a.getAppointmentTime(), a.getStatus(),
                    a.getTokenNumber() == null ? "" : a.getTokenNumber(),
                    a.getTotalCost()
            });
        }
    }
}
