package view;

import controller.DoctorController;

import javax.swing.*;
import java.sql.Date;
import java.sql.Time;

/**
 * NetBeans GUI Builder form (paired ScheduleDialog.form) - edit via Design tab.
 */
public class ScheduleDialog extends JDialog {

    private final DoctorController doctorController;
    private final int doctorId;
    private boolean added = false;

    public ScheduleDialog(JFrame parent, DoctorController doctorController, int doctorId) {
        super(parent, "Add Available Time Slot", true);
        this.doctorController = doctorController;
        this.doctorId = doctorId;
        initComponents();
        buildFriendlyLayout();
        getRootPane().setDefaultButton(saveButton);
        UITheme.style(this);
        setMinimumSize(new java.awt.Dimension(520, 360));
        setSize(520, 380);
        setResizable(false);
        setLocationRelativeTo(parent);
    }

    private void buildFriendlyLayout() {
        JPanel root = new JPanel(new java.awt.BorderLayout(0, 16));
        root.setBorder(BorderFactory.createEmptyBorder(22, 24, 22, 24));

        JLabel title = new JLabel("Add Available Time Slot");
        title.setFont(title.getFont().deriveFont(java.awt.Font.BOLD, 22f));
        title.setForeground(UITheme.PRIMARY_DARK);
        title.putClientProperty("ui.preserveForeground", Boolean.TRUE);
        JLabel help = new JLabel("Choose a date and the time range when you are available.");
        help.setForeground(UITheme.MUTED);
        help.putClientProperty("ui.preserveForeground", Boolean.TRUE);
        JPanel heading = new JPanel();
        heading.setLayout(new BoxLayout(heading, BoxLayout.Y_AXIS));
        heading.add(title);
        heading.add(Box.createVerticalStrut(5));
        heading.add(help);
        root.add(heading, java.awt.BorderLayout.NORTH);

        JPanel form = new JPanel(new java.awt.GridBagLayout());
        form.setBackground(UITheme.SURFACE);
        form.putClientProperty("ui.preserveBackground", Boolean.TRUE);
        form.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(UITheme.BORDER),
                BorderFactory.createEmptyBorder(16, 18, 16, 18)));
        java.awt.GridBagConstraints constraints = new java.awt.GridBagConstraints();
        constraints.insets = new java.awt.Insets(7, 7, 7, 7);
        constraints.anchor = java.awt.GridBagConstraints.WEST;
        constraints.fill = java.awt.GridBagConstraints.HORIZONTAL;

        addFormRow(form, constraints, 0, dateLabel, dateField);
        addFormRow(form, constraints, 1, startLabel, startField);
        addFormRow(form, constraints, 2, endLabel, endField);
        dateField.setPreferredSize(new java.awt.Dimension(330, 38));
        startField.setPreferredSize(new java.awt.Dimension(330, 38));
        endField.setPreferredSize(new java.awt.Dimension(330, 38));
        root.add(form, java.awt.BorderLayout.CENTER);

        JPanel actions = new JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 0, 0));
        JButton cancelButton = new JButton("Cancel");
        cancelButton.addActionListener(event -> dispose());
        saveButton.setPreferredSize(new java.awt.Dimension(150, 42));
        actions.add(cancelButton);
        actions.add(Box.createHorizontalStrut(10));
        actions.add(saveButton);
        root.add(actions, java.awt.BorderLayout.SOUTH);
        setContentPane(root);
    }

    private void addFormRow(JPanel panel, java.awt.GridBagConstraints constraints, int row,
            JLabel label, java.awt.Component field) {
        label.setFont(label.getFont().deriveFont(java.awt.Font.BOLD));
        constraints.gridy = row;
        constraints.gridx = 0;
        constraints.weightx = 0;
        panel.add(label, constraints);
        constraints.gridx = 1;
        constraints.weightx = 1;
        panel.add(field, constraints);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateLabel = new javax.swing.JLabel();
        dateField = DateTimePicker.datePicker();
        startLabel = new javax.swing.JLabel();
        startField = DateTimePicker.timePicker(9, 0);
        endLabel = new javax.swing.JLabel();
        endField = DateTimePicker.timePicker(9, 30);
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        dateLabel.setText("Available date:");

        startLabel.setText("Start time:");

        endLabel.setText("End time:");

        saveButton.setText("Add Slot");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveButton, javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(endLabel)
                            .addComponent(startLabel)
                            .addComponent(dateLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(endField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLabel)
                    .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startLabel)
                    .addComponent(startField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endLabel)
                    .addComponent(endField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(saveButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            Date date = DateTimePicker.sqlDate(dateField);
            Time start = DateTimePicker.sqlTime(startField);
            Time end = DateTimePicker.sqlTime(endField);
            if (!end.after(start)) {
                throw new IllegalArgumentException("End time must be after start time.");
            }
            doctorController.addSlot(doctorId, date, start, end);
            added = true;
            dispose();
        } catch (Exception ex) {
            UITheme.showMessageDialog(this, ex.getMessage(), "Check Time Slot", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    public boolean wasAdded() { return added; }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CalendarDatePicker dateField;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JComboBox<java.time.LocalTime> endField;
    private javax.swing.JLabel endLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox<java.time.LocalTime> startField;
    private javax.swing.JLabel startLabel;
    // End of variables declaration//GEN-END:variables
}
