package view;

import controller.DoctorController;

import javax.swing.*;
import java.sql.Date;
import java.sql.Time;

/**
 * NetBeans GUI Builder form (paired ScheduleDialog.form) - edit via Design tab.
 */
public class ScheduleDialog extends JDialog {

    private final DoctorController doctorController;
    private final int doctorId;
    private boolean added = false;

    public ScheduleDialog(JFrame parent, DoctorController doctorController, int doctorId) {
        super(parent, "Add Available Time Slot", true);
        this.doctorController = doctorController;
        this.doctorId = doctorId;
        initComponents();
        UITheme.style(this);
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateLabel = new javax.swing.JLabel();
        dateField = DateTimePicker.datePicker();
        startLabel = new javax.swing.JLabel();
        startField = DateTimePicker.timePicker(9, 0);
        endLabel = new javax.swing.JLabel();
        endField = DateTimePicker.timePicker(9, 30);
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        dateLabel.setText("Available date:");

        startLabel.setText("Start time:");

        endLabel.setText("End time:");

        saveButton.setText("Add Slot");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveButton, javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(endLabel)
                            .addComponent(startLabel)
                            .addComponent(dateLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(endField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLabel)
                    .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startLabel)
                    .addComponent(startField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endLabel)
                    .addComponent(endField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(saveButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            Date date = DateTimePicker.sqlDate(dateField);
            Time start = DateTimePicker.sqlTime(startField);
            Time end = DateTimePicker.sqlTime(endField);
            if (!end.after(start)) {
                throw new IllegalArgumentException("End time must be after start time.");
            }
            doctorController.addSlot(doctorId, date, start, end);
            added = true;
            dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Check the date/time format:\n" + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    public boolean wasAdded() { return added; }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CalendarDatePicker dateField;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JComboBox<java.time.LocalTime> endField;
    private javax.swing.JLabel endLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox<java.time.LocalTime> startField;
    private javax.swing.JLabel startLabel;
    // End of variables declaration//GEN-END:variables
}
